# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.2
loader_version=0.16.9

# Mod Properties
mod_name=Particular
mod_version=1.1.1+1.21.4
maven_group=com.chailotl.particular
archives_base_name=particular

# Dependencies
fabric_version=0.112.2+1.21.4
owo_version=0.12.19+1.21.4
sushi_version=0.2.1+1.21
seasons_version=2.2.1+1.20